# -*- coding: utf-8 -*-
"""MNIST_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPP2rzP1hSFdgLBiJevwSczdrdPfaicG

MNIST_Dataset
"""

import pandas as pd
import torch
import torch.optim as optim
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

torch.manual_seed(42)

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device {device}')

transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307),(0.3801))
])

train_data=datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

test_data=datasets.MNIST(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

len(test_data)

image, label = train_data[0]

print(image.shape)   # (1, 28, 28)
print(label)         # 0–9

Train_dataloader=DataLoader(train_data,batch_size=32,shuffle=True)
Test_dataloader=DataLoader(test_data,batch_size=32,shuffle=False)

"""Building Model

"""

class My_CNN(nn.Module):

  def __init__(self,in_channels):
    super().__init__()

    self.feature=nn.Sequential(
        nn.Conv2d(in_channels,32,kernel_size=3,padding=1),
        nn.BatchNorm2d(32),
        nn.ReLU(),
        nn.Dropout2d(0.1),
        nn.MaxPool2d(kernel_size=2,stride=2),

        nn.Conv2d(32,64,kernel_size=3,padding=1),
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.Dropout2d(0.1),
        nn.MaxPool2d(kernel_size=2,stride=2),

    )
    self.classifier=nn.Sequential(
        nn.Flatten(),
        nn.Linear(64*7*7,128),
        nn.BatchNorm1d(128),
        nn.ReLU(),
        nn.Dropout(0.3),

        nn.Linear(128,64),
        nn.BatchNorm1d(64),
        nn.ReLU(),
        nn.Dropout(0.3),

        nn.Linear(64,10)

    )

  def forward(self,data):
    data=self.feature(data)
    data=self.classifier(data)

    return data

# Parameters

epochs=3
learning_rate=0.01

in_channel=1

# Model object
model=My_CNN(in_channel)
model.to(device)

# Loss
criterion=nn.CrossEntropyLoss()

# optimizer
optimizer=optim.Adam(model.parameters(),lr=learning_rate)

# training loop

for epoch in range(epochs):

  total=0

  for feature ,label in Train_dataloader:

    feature,label=feature.to(device),label.to(device)

    # forward pass
    y_pred=model(feature)

    # loss
    loss=criterion(y_pred,label)

    # backward
    optimizer.zero_grad()
    loss.backward()

    # update
    optimizer.step()

    total+=loss

  print(f'Epoch :{epoch+1}, loss : {total/len(Train_dataloader)}')


total=0
correct=0

model.eval()

with torch.no_grad():

  for feature ,label in Test_dataloader:

    feature,label=feature.to(device),label.to(device)

    # forward pass
    y_pred=model(feature)

    _,predict=torch.max(y_pred,1)

    total+=len(feature)

    correct+=(predict==label).sum().item()

  accuracy=correct/total

  print(accuracy)

predicted_value=[]
label_value=[]


with torch.no_grad():

  for feature ,label in Train_dataloader:



    feature,label=feature.to(device),label.to(device)

    label_value.append(label)

    # forward pass
    y_pred=model(feature)

    _,predict=torch.max(y_pred,1)

    predicted_value.append(predict)

    total+=len(feature)

    correct+=(predict==label).sum().item()

  accuracy=correct/total

  print(accuracy)

predicted_val=torch.cat(predicted_value[:])
label_val=torch.cat(label_value[:])
predicted_val[:40
              ]

label_val=label_val.cpu().numpy()
predicted_val=predicted_val.cpu().numpy()
label_val

from sklearn.metrics import confusion_matrix

cm=confusion_matrix(predicted_val,label_val,labels=[0,1,2,3,4,5,6,7,8,9])
cm

